<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "templates_aide"
 *
 * Auto generated by Extension Builder 2020-04-26
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'Templates Aide',
    'description' => '',
    'category' => 'plugin',
    'author' => 'Philipp Dieter',
    'author_email' => 'philippdieter@attic-media.net',
    'state' => 'alpha',
    'uploadfolder' => 0,
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '0.0.1',
    'constraints' => [
        'depends' => [
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
